# Gmail configuration
gmail_password = "AxisNir1103@15051998"  

#gmail_password = "xxxx"

[google_oauth.installed]
client_id = "282009328071-amn7gfm4c3ggajdv82edor98o2tn1v27.apps.googleusercontent.com"
project_id = "invigilator-app-501412"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_secret = "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"
redirect_uris = ["http://localhost"]
